<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15665" started-at="2019-07-16T16:34:45Z" finished-at="2019-07-16T16:35:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15665" started-at="2019-07-16T16:34:45Z" finished-at="2019-07-16T16:35:01Z">
      <class name="DemoAuto.DemoRegisterTest">
        <test-method status="PASS" signature="initialization()[pri:0, instance:DemoAuto.DemoRegisterTest@51565ec2]" name="initialization" is-config="true" duration-ms="7197" started-at="2019-07-16T12:34:45Z" finished-at="2019-07-16T12:34:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method status="FAIL" signature="DemoRegister()[pri:0, instance:DemoAuto.DemoRegisterTest@51565ec2]" name="DemoRegister" duration-ms="8439" started-at="2019-07-16T12:34:52Z" finished-at="2019-07-16T12:35:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The copy right contains test
Expected: a string containing "@ 2016 Automation Testing All Rights Reserved"
     but: was ""@ 2016"Automation Testing"All Rights Reserved.""]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The copy right contains test
Expected: a string containing "@ 2016 Automation Testing All Rights Reserved"
     but: was ""@ 2016"Automation Testing"All Rights Reserved.""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at DemoAuto.DemoRegisterTest.DemoRegister(DemoRegisterTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DemoRegister -->
      </class> <!-- DemoAuto.DemoRegisterTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
